CREATE TABLE IF NOT EXISTS photo (
  ticket_id INTEGER NOT NULL,
  image TEXT DEFAULT NULL,
  image_url VARCHAR(200) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(ticket_id),
  FOREIGN KEY (ticket_id) REFERENCES ticket (id) ON DELETE NO ACTION ON UPDATE NO ACTION
); 