CREATE TABLE `ticket` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `event_id` int(10) unsigned DEFAULT NULL,
  `user_id` int(10) unsigned DEFAULT NULL,
  `category_id` int(10) unsigned DEFAULT NULL,
  `ticket_source_event_id` int(10) unsigned DEFAULT NULL,
  `code` varchar(100) DEFAULT NULL,
  `fullname` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `documentId` varchar(255) DEFAULT NULL,
  `extrafield1` varchar(255) DEFAULT NULL,
  `extrafield2` varchar(255) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT 0,
  `master` tinyint(1) NOT NULL DEFAULT 0,
  `accredited_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code_event` (`event_id`,`code`),
  KEY `category_id` (`category_id`),
  KEY `ticket_source_event_id` (`ticket_source_event_id`),
  KEY `code` (`code`),
  KEY `fullname` (`fullname`),
  KEY `event_id` (`event_id`),
  KEY `user_id` (`user_id`),
  KEY `email` (`email`),
  KEY `documentId` (`documentId`),
  KEY `extrafield1` (`extrafield1`),
  KEY `extrafield2` (`extrafield2`),
  CONSTRAINT `fk_ticket_category_id` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_event_id` FOREIGN KEY (`event_id`) REFERENCES `event` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_ticket_source_ev_id` FOREIGN KEY (`ticket_source_event_id`) REFERENCES `ticket_source_event` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;