CREATE TABLE IF NOT EXISTS event (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  created_by INT UNSIGNED NOT NULL,
  name VARCHAR(100) DEFAULT NULL,
  startdate DATETIME DEFAULT NULL,
  enddate DATETIME DEFAULT NULL,
  active TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  local TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_event_created_by (created_by),
  KEY idx_name (name),
  KEY idx_startdate (startdate),
  KEY idx_enddate (enddate),
  KEY idx_period (startdate, enddate),
  KEY idx_active (active),
  KEY idx_local (local(1)),
  KEY idx_created_at (created_at),
  KEY idx_updated_at (updated_at),
  KEY idx_deleted_at (deleted_at),
  CONSTRAINT fk_event_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci; 